cat("\014")
rm(list=ls())
X_test<-read.table("X_test.txt")
Y_test<-read.table("y_test.txt",col.names="Activity")
subject_test<-read.table("subject_test.txt",col.names="Subject")
X_train<-read.table("X_train.txt")
Y_train<-read.table("y_train.txt",col.names="Activity")
subject_train<-read.table("subject_train.txt",col.names="Subject")
test <- cbind(subject_test,Y_test,X_test)
train <- cbind(subject_train,Y_train,X_train)
all <- rbind(test,train)
features<-read.table("features.txt")
setnames(all, names(all)[3:length(names(all))], as.character(features[,2]))
activity_labels<-read.table("activity_labels.txt")
all$Activity<-sapply(all$Activity, function(x) activity_labels[which(activity_labels[,1] %in% x),2])
m<-c("TRUE","TRUE",grepl("mean", features[,2]) | grepl("std", features[,2]))
all<-all[,which(m %in% "TRUE")]
all<-all[,1:72]
all<-melt(all,id=c("Activity","Subject"), measure.vars=names(all)[3:72])
tidy_data <- dcast(all, Subject + Activity ~ variable, mean)
write.table(tidy_data,file="tidy_data.txt")